/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.admin.productos;

import clases.Producto;
import clases.estructuras.Dato;
import clases.estructuras.Nodo;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ventanas.admin.vProducto;
import ventanas.vLogin;

/**
 *
 * @author Jo
 */
public class vModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form vModificarProducto
     * @param producto
     */
    public vModificarProducto(Producto producto) {
        this.producto=producto;
        initComponents(); 
        rellenarInfo();        
        setLocationRelativeTo(null);
    }

    private vModificarProducto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lModificar = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lDescripcion = new javax.swing.JLabel();
        lPrecio = new javax.swing.JLabel();
        lExistencia = new javax.swing.JLabel();
        lImagen = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tDescripcion = new javax.swing.JTextField();
        tImagen = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bGuardar = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        tExistencia = new javax.swing.JFormattedTextField();
        tPrecio = new javax.swing.JFormattedTextField();
        lNuevo = new javax.swing.JLabel();
        tActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        lModificar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lModificar.setText("Modificar producto");

        lNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNombre.setText("Nombre: ");

        lDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lDescripcion.setText("Descripción: ");

        lPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPrecio.setText("Precio actual: ");

        lExistencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lExistencia.setText("Existencia: ");

        lImagen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lImagen.setText("Imagen: ");

        tNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tImagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tImagen.setEnabled(false);

        bBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/buscar.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/guardar.png"))); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/regresar.png"))); // NOI18N
        bRegresar.setText("Regresar");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/exit.png"))); // NOI18N
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        tExistencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        tExistencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            tPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNuevo.setText("Precio nuevo:");

        tActual.setEditable(false);
        tActual.setBackground(new java.awt.Color(255, 255, 255));
        tActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lModificar)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bGuardar)
                .addGap(18, 18, 18)
                .addComponent(bRegresar)
                .addGap(18, 18, 18)
                .addComponent(bSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPrecio)
                            .addComponent(lDescripcion)
                            .addComponent(lNombre))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(tDescripcion, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tActual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lExistencia)
                            .addComponent(lImagen)
                            .addComponent(lNuevo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(bBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecio)
                    .addComponent(tActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNuevo)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lExistencia)
                    .addComponent(tExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lImagen)
                    .addComponent(bBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bRegresar)
                    .addComponent(bSalir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        producto.setDescripcion(tDescripcion.getText());
        producto.setExistencia((int)tExistencia.getValue());
        producto.setImagen(tImagen.getText());
        producto.setNombre(tNombre.getText());
        producto.setPrecio(Float.parseFloat(tPrecio.getText()));      
        datos.getProductos().buscar(producto).setInfo(producto);      
        vProducto ventana = new vProducto();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        vProducto ventana = new vProducto();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        vLogin ventana = new vLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        JFileChooser imagen = new JFileChooser();
        imagen.showOpenDialog(this);
        File ruta = imagen.getSelectedFile();
        if(ruta!=null) try {
            tImagen.setText(ruta.getCanonicalPath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error, dirección incorrecta");
        }
        else tImagen.setText(" ");
    }//GEN-LAST:event_bBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lExistencia;
    private javax.swing.JLabel lImagen;
    private javax.swing.JLabel lModificar;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNuevo;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JTextField tActual;
    private javax.swing.JTextField tDescripcion;
    private javax.swing.JFormattedTextField tExistencia;
    private javax.swing.JTextField tImagen;
    private javax.swing.JTextField tNombre;
    private javax.swing.JFormattedTextField tPrecio;
    // End of variables declaration//GEN-END:variables
    Dato datos = new Dato();
    Nodo auxiliar = new Nodo();
    Producto producto = new Producto();
    
    private void rellenarInfo(){  
        try{
            tNombre.setText(producto.getNombre());
            tDescripcion.setText(producto.getDescripcion());
            tImagen.setText(producto.getImagen());
            tActual.setText(String.valueOf(producto.getPrecio()));
            tExistencia.setValue(producto.getExistencia());            
        }catch(Exception e){
            
        }

    }
}
