/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.usuario;

import clases.Cliente;
import clases.Oferta;
import clases.Producto;
import clases.estructuras.Dato;
import clases.estructuras.Nodo;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import ventanas.vLogin;

/**
 *
 * @author Jo
 */
public class vInicio extends javax.swing.JFrame {

    /**
     * Creates new form vInicio
     * @param usuario el nombre del usuario
     * @param cliente el cliente logueado
     */
    public vInicio(String usuario, Cliente cliente) {
        this.usuario=usuario;  
        this.cliente=cliente;
        initComponents();
        try{
            agregarProductos();    
        }catch(Exception e){
            
        }
        lBienvenida.setText("Hola, "+usuario);
        setLocationRelativeTo(null);
    }

    private vInicio() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lBienvenida = new javax.swing.JLabel();
        bCarrito = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lOfertas = new javax.swing.JLabel();
        sOfertas = new javax.swing.JScrollPane();
        pOfertas = new javax.swing.JPanel();
        bProductos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lTiendecita = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setResizable(false);

        lBienvenida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lBienvenida.setText("Hola usuario");

        bCarrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/carrito.png"))); // NOI18N
        bCarrito.setText("Carrito");

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/exit.png"))); // NOI18N
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bPagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/pagar.png"))); // NOI18N
        bPagar.setText("Pagar");

        lOfertas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lOfertas.setText("Ofertas");

        pOfertas.setLayout(new java.awt.GridLayout(0, 3));
        sOfertas.setViewportView(pOfertas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(lOfertas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lOfertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        bProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/ingresar.png"))); // NOI18N
        bProductos.setText("Ir a productos de tiendecita");
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });

        lTiendecita.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lTiendecita.setText("Tiendecita");

        bModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/modificar.png"))); // NOI18N
        bModificar.setText("Modificar perfil");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bProductos)
                .addGap(313, 313, 313))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(lTiendecita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lBienvenida))
                    .addComponent(bModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCarrito)
                        .addComponent(bPagar)
                        .addComponent(bSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTiendecita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bProductos)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        vModificarPerfil ventana = new vModificarPerfil(usuario, cliente);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        vLogin ventana = new vLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        vProductoTienda ventana = new vProductoTienda(usuario,cliente);
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCarrito;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bPagar;
    private javax.swing.JButton bProductos;
    private javax.swing.JButton bSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JLabel lOfertas;
    private javax.swing.JLabel lTiendecita;
    private javax.swing.JPanel pOfertas;
    private javax.swing.JScrollPane sOfertas;
    // End of variables declaration//GEN-END:variables
    String usuario;
    Cliente cliente = new Cliente();    
    Nodo auxiliar = new Nodo();
    Nodo auxiliar2 = new Nodo();
    Dato dato = new Dato();
    Oferta oferta = new Oferta();
    Producto producto = new Producto();


    /**
     * Dibuja paneles que contienen toda la información de las ofertas existentes
     */    
    private void dibujarProductos(String nombre, String precio, String anterior,String i){
        JPanel panelPrincipal = new JPanel();
        JPanel panelImagen = new JPanel();
        JLabel imagen = new JLabel();
        Border lineaNegra = BorderFactory.createLineBorder(Color.black);
        JTextArea area = new JTextArea(2,2);
        area.setText(nombre);
        JButton boton = new JButton("Antes: "+anterior+" Ahora: "+precio);
        boton.setIcon(new ImageIcon("C:\\Users\\Jo\\Documents\\NetBeansProjects\\Proyecto2\\src\\imagenes\\iconos\\carrito.png"));
        imagen.setIcon(new ImageIcon(i));
        

        panelPrincipal.setSize(265, 299);
        panelPrincipal.setLayout(new BoxLayout(panelPrincipal,BoxLayout.PAGE_AXIS));
        panelImagen.setSize(34, 223);
//        panelImagen.setBackground(Color.BLUE);
        panelImagen.setBorder(lineaNegra);
        panelImagen.add(imagen);
        imagen.setAlignmentX(CENTER_ALIGNMENT);
        boton.setAlignmentX(CENTER_ALIGNMENT); 
        area.setAlignmentX(CENTER_ALIGNMENT);
        area.setEditable(false);
        boton.setSize(73, 23);   
        area.setBackground(new Color(0,0,0,0));
        area.setBorder(BorderFactory.createEmptyBorder());
        area.setLineWrap(true);
        panelPrincipal.add(panelImagen);
        panelPrincipal.add(area);
        panelPrincipal.add(boton); 
        Border border = panelPrincipal.getBorder();
        Border margin = new EmptyBorder(5,5,5,5);
        panelPrincipal.setBorder(new CompoundBorder(border, margin));        
        pOfertas.add(panelPrincipal); 
    }


    /**
     * Agrega todas las oferta existentes al componente padre
     */    
    private void agregarProductos(){
        auxiliar = dato.getOfertas().getInicio();
        oferta = (Oferta) auxiliar.getInfo();
        auxiliar2 = oferta.getProductos().getPrimero();
        producto = (Producto) auxiliar2.getInfo();
        for(int i=0; i<dato.getOfertas().getTamaño();i++){
            for(int j=0;j<oferta.getProductos().getTamaño();j++){
                dibujarProductos(producto.getNombre(),String.valueOf(Math.round(producto.getPrecio()*100)/100d),String.valueOf(producto.getPrecioAnterior()),producto.getImagen());
                auxiliar2= auxiliar2.getSiguiente();
                producto = (Producto) auxiliar2.getInfo(); 
            } 
            auxiliar = auxiliar.getSiguiente();
            oferta = (Oferta) auxiliar.getInfo();
            auxiliar2 = oferta.getProductos().getPrimero();
            producto = (Producto) auxiliar2.getInfo();            
        }
        
    }
}
