/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.usuario;

import clases.Cliente;
import clases.Oferta;
import clases.Producto;
import clases.estructuras.Dato;
import clases.estructuras.ListaCircularSimple;
import clases.estructuras.Nodo;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import ventanas.vLogin;

/**
 *
 * @author Jo
 */
public class vProductoTienda extends javax.swing.JFrame {

    /**
     * Creates new form vProductosTienda
     * @param usuario el nombre del usuario
     * @param cliente el cliente logueado
     */
    public vProductoTienda(String usuario, Cliente cliente) {
        this.usuario=usuario;
        this.cliente=cliente;
        initComponents();
        agregarProductos();
        lBienvenida.setText("Hola, "+usuario);
        setLocationRelativeTo(null);
    }

    private vProductoTienda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lBienvenida = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        bCarrito = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();
        lProductos = new javax.swing.JLabel();
        sOfertas = new javax.swing.JScrollPane();
        pOfertas = new javax.swing.JPanel();
        bRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");
        setPreferredSize(new java.awt.Dimension(893, 720));
        setResizable(false);

        lBienvenida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lBienvenida.setText("Hola usuario");

        bModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/modificar.png"))); // NOI18N
        bModificar.setText("Modificar perfil");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bCarrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/carrito.png"))); // NOI18N
        bCarrito.setText("Carrito");

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/exit.png"))); // NOI18N
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bPagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/pagar.png"))); // NOI18N
        bPagar.setText("Pagar");

        lProductos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lProductos.setText("Productos disponibles");

        sOfertas.setPreferredSize(new java.awt.Dimension(873, 417));

        pOfertas.setLayout(new java.awt.GridLayout(0, 3));
        sOfertas.setViewportView(pOfertas);

        bRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/regresar.png"))); // NOI18N
        bRegresar.setText("Regresar");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lBienvenida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(lProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lBienvenida)
                    .addComponent(bModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCarrito)
                        .addComponent(bPagar)
                        .addComponent(bSalir))
                    .addComponent(bRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        vLogin ventana = new vLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        vModificarPerfil ventana = new vModificarPerfil(usuario,cliente);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        vInicio ventana = new vInicio(usuario,cliente);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vProductoTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vProductoTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vProductoTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vProductoTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new vProductoTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCarrito;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bPagar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBienvenida;
    private javax.swing.JLabel lProductos;
    private javax.swing.JPanel pOfertas;
    private javax.swing.JScrollPane sOfertas;
    // End of variables declaration//GEN-END:variables
    String usuario;
    Cliente cliente = new Cliente();
    Nodo auxiliar = new Nodo();
    Nodo auxiliar2 = new Nodo();
    Nodo auxiliar3 = new Nodo();
    Dato dato = new Dato();
    Oferta oferta = new Oferta();
    Producto producto = new Producto();
    Producto producto2 = new Producto();
    ListaCircularSimple productosRepetidos = new ListaCircularSimple();
    
    /**
     * Dibuja los paneles que contienen toda la información de las ofertas existentes
     */    
    private void dibujarProductos(String nombre, String precio, String anterior,String i){
        JPanel panelPrincipal = new JPanel();
        JPanel panelImagen = new JPanel();
        JLabel imagen = new JLabel();
        Border lineaNegra = BorderFactory.createLineBorder(Color.black);
        JTextArea area = new JTextArea(2,2);
        area.setText(nombre);
        JButton boton = new JButton("Antes: "+anterior+" Ahora: "+precio);
        boton.setIcon(new ImageIcon("C:\\Users\\Jo\\Documents\\NetBeansProjects\\Proyecto2\\src\\imagenes\\iconos\\carrito.png"));
        imagen.setIcon(new ImageIcon(i));
        

        panelPrincipal.setSize(265, 299);
        panelPrincipal.setLayout(new BoxLayout(panelPrincipal,BoxLayout.PAGE_AXIS));
        panelImagen.setSize(34, 223);
//        panelImagen.setBackground(Color.BLUE);
        panelImagen.setBorder(lineaNegra);
        panelImagen.add(imagen);
        imagen.setAlignmentX(CENTER_ALIGNMENT);
        boton.setAlignmentX(CENTER_ALIGNMENT); 
        area.setAlignmentX(CENTER_ALIGNMENT);
        boton.setSize(73, 23);   
        area.setBackground(new Color(0,0,0,0));
        area.setBorder(BorderFactory.createEmptyBorder());
        area.setLineWrap(true);
        area.setEditable(false);        
        panelPrincipal.add(panelImagen);
        panelPrincipal.add(area);
        panelPrincipal.add(boton); 
        Border border = panelPrincipal.getBorder();
        Border margin = new EmptyBorder(5,5,5,5);
        panelPrincipal.setBorder(new CompoundBorder(border, margin));        
        pOfertas.add(panelPrincipal); 
    }
 
    
    /**
     * Agrega los paneles creados con la información de todas las ofertas al componente padre
     */    
    private void dibujarProductos(String nombre, String precio, String i){

        JPanel panelPrincipal = new JPanel();
        JPanel panelImagen = new JPanel();
        JLabel imagen = new JLabel();
        Border lineaNegra = BorderFactory.createLineBorder(Color.black);
        JTextArea area = new JTextArea(2,2);
        area.setText(nombre);
        JButton boton = new JButton("Precio: Q."+precio);
        boton.setIcon(new ImageIcon("C:\\Users\\Jo\\Documents\\NetBeansProjects\\Proyecto2\\src\\imagenes\\iconos\\carrito.png"));
        imagen.setIcon(new ImageIcon(i));
        

        panelPrincipal.setSize(265, 299);
        panelPrincipal.setLayout(new BoxLayout(panelPrincipal,BoxLayout.PAGE_AXIS));
        panelImagen.setSize(34, 223);
//        panelImagen.setBackground(Color.BLUE);
        panelImagen.setBorder(lineaNegra);
        panelImagen.add(imagen);
        imagen.setAlignmentX(CENTER_ALIGNMENT);
        boton.setAlignmentX(CENTER_ALIGNMENT); 
        area.setAlignmentX(CENTER_ALIGNMENT);
        boton.setSize(73, 23);   
        area.setBackground(new Color(0,0,0,0));
        area.setBorder(BorderFactory.createEmptyBorder());
        area.setLineWrap(true);
        panelPrincipal.add(panelImagen);
        panelPrincipal.add(area);
        panelPrincipal.add(boton); 
        Border border = panelPrincipal.getBorder();
        Border margin = new EmptyBorder(5,5,5,5);
        panelPrincipal.setBorder(new CompoundBorder(border, margin));        
        pOfertas.add(panelPrincipal);           
    }


    /**
     * Agrega los productos sin ofertas al componente padre
     */    
    private void agregarProductos(){
        boolean repetido=false;
        
        try{
            
            auxiliar3 = dato.getProductos().getPrimero();
            producto2 = (Producto)auxiliar3.getInfo(); 
            
        }catch(Exception e){
            
        }

        
        // Agregando ofertas----------------------------------------------------
        try{
            auxiliar = dato.getOfertas().getInicio();
            oferta = (Oferta) auxiliar.getInfo();
            auxiliar2 = oferta.getProductos().getPrimero();
            producto = (Producto) auxiliar2.getInfo();

            for(int i=0; i<dato.getOfertas().getTamaño();i++){

                for(int j=0;j<oferta.getProductos().getTamaño();j++){
                    dibujarProductos(producto.getNombre(),String.valueOf(Math.round(producto.getPrecio()*100)/100d),String.valueOf
                    (producto.getPrecioAnterior()),producto.getImagen());
                    productosRepetidos.agregar(producto);
                    auxiliar2= auxiliar2.getSiguiente();
                    producto = (Producto) auxiliar2.getInfo(); 
                }
                try{

                    auxiliar = auxiliar.getSiguiente();
                    oferta = (Oferta) auxiliar.getInfo();
                    auxiliar2 = oferta.getProductos().getPrimero();
                    producto = (Producto) auxiliar2.getInfo(); 

                }catch(Exception e){
                    
                }
           
            }     
            auxiliar = dato.getOfertas().getInicio();
            oferta = (Oferta) auxiliar.getInfo();
            auxiliar2 = oferta.getProductos().getPrimero();
            producto = (Producto) auxiliar2.getInfo();  
            
        }catch(Exception e){
            
        }
        
        //Agregando ofertas-----------------------------------------------------
        
        
        //Agregando producto valuando las ofertas-------------------------------
        
        try{
            
            auxiliar2 = productosRepetidos.getPrimero();
            producto = (Producto) auxiliar2.getInfo();          
            for(int j=0;j<dato.getProductos().getTamaño();j++){

                for(int i=0;i<productosRepetidos.getTamaño();i++){
                    if(producto2.getId().equals(producto.getId())){
                        repetido=true;
                        break;
                    }
                    auxiliar2 = auxiliar2.getSiguiente();
                    producto = (Producto) auxiliar2.getInfo();         
                }
                if(repetido){
                    repetido=false;
                }else{
                    dibujarProductos(producto2.getNombre(),String.valueOf(producto2.getPrecio()),producto2.getImagen());                
                }
                auxiliar2 = productosRepetidos.getPrimero();
                producto = (Producto) auxiliar2.getInfo(); 
                auxiliar3 = auxiliar3.getSiguiente();
                producto2 = (Producto)auxiliar3.getInfo();                    

            }            
            
        }catch(Exception e){

            for(int j=0;j<dato.getProductos().getTamaño();j++){
                dibujarProductos(producto2.getNombre(),String.valueOf(producto2.getPrecio()),producto2.getImagen());                
                auxiliar3 = auxiliar3.getSiguiente();
                producto2 = (Producto)auxiliar3.getInfo();                    
            }   
        }
        
        

        
        //Agregando producto valuando las ofertas------------------------------
        

       
    }     
}



